name: scan24-test_shape

####network#####
network: shape
database_name: volsdf/scan24-test
apply_occ_loss: true
occ_loss_step: 20000
clip_sample_variance: false

######loss######
loss: ['nerf_render','eikonal','std','init_sdf_reg','occ']
val_metric: ['shape_render']
key_metric_name: psnr
eikonal_weight: 0.1
freeze_inv_s_step: 15000

####dataset#####
train_dataset_type: dummy
dataset_dir: data/DTU
train_dataset_cfg:
  database_name: volsdf/scan24-test
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: volsdf/scan24-test

####trainier####
optimizer_type: adam
lr_type: warm_up_cos
lr_cfg: {}
total_step: 300000
val_interval: 5000
save_interval: 1000
train_log_step: 20

